### PR TITLE
Provide toggle between set/unset BA in PostControls or Post footer

### PR DESCRIPTION
**Pull request by imorland**
Providing a toggle option to switch between having set/unset actions in either `PostControls` or post footer.

Screenshot 2020-02-07 at 19 06 17

Screenshot 2020-02-07 at 19 07 38

vs

Screenshot 2020-02-07 at 19 08 27

### CODE REVIEW

**Comment by imorland** [comment]
Opening this PR early to gather feedback whilst I complete.

Still to-do
- Refactoring `addBestAnswerAction.js`
- CSS

**Comment by datitisev** [comment]
FYI - you can create a draft PR without putting WIP in the name.

Is the button styling in the new layout going to be included with the PR? I assume that's just how you have it styled at giffgaff but just wanted to make sure.

**Comment by imorland** [comment]
I keep forgetting about the draft PR feature! I'll try and remember 😉 

I wasn't going to include the giffgaff specific styling, but intend to include some basic style. Does that work for you?

**Comment by datitisev** [comment]
I think, depending on what that basic style is :P.

**Comment by imorland** [comment]
@datitisev could I please ask for a review on the changes so far, excluding the styling?

**Comment by datitisev** [comment]
Hm, a few things, not really that big - I would move the functions to outside the initializer & before the initializer is added, as I had to scroll a bit to find where the functions were declared.

I also just noticed that the locale & settings are all using hyphens instead of underscores - that's my bad for not noticing earlier. You can fix that in this PR or I'll do so myself after merging.

**Comment by imorland** [comment]
My fault for the hyphens, will correct in the next commit

**Comment by datitisev** [comment]
@imorland Can you provide a screenshot for the current style of the button with the alternate layout?

**Comment by imorland** [comment]
3 states:

No BA set
Screenshot 2020-02-07 at 23 29 49

BA set on current post
Screenshot 2020-02-07 at 23 30 04

BA set on other post
Screenshot 2020-02-07 at 23 30 14

**Comment by datitisev** [comment]
Ah, the black bg is the primary color. Looks good to me, I'll merge it and test it out locally and fix whatever needs fixing.

Thanks!!

**Comment by imorland** [comment]
Perfect, thanks!

This is the last PR in this series. I will be adding one more in due course, perhaps in a week or so to add the filter option, FYI

Feel free to release when ready 🙂

**Comment by imorland** [comment]
Yes, I was using a giffgaff Flarum install for this one with the main theme disabled, rather than a vanilla Flarum. Sorry about that

**Comment by imorland** [comment]
@datitisev have you managed to look at this one locally yet? Just wondering on it's progress really :)

**Comment by datitisev** [comment]
@imorland No sorry, let me do that now. I was out all day today.

**Pull request merged**
