### PR TITLE
Add timestamp to best answer

### PR DESCRIPTION
**Pull request by imorland**
At giffgaff we are currently using a fork of the old wiwatsrt version of best answers, with some of our own changes. This PR is the beginning of us making the switch over to fof/best-answer, and sharing our customizations and improvements.

@datitisev - I'm guessing to keep things simple, a seperate PR for each feature would be preferred, so here's the first :)

Here, we are logging the timestamp for when a best answer is set, and displaying it alongside the user who set it.

Customizable or removable via the locale file

Screenshot:
image

### CODE REVIEW

**Comment by datitisev** [comment]
Hello! Thanks for the PR. Overall looks good.

The only things that jump out at me is that the client-side code for the set at time is a bit weird, especially as you seem to be pushing the attribute again later - and it's completely ignored by the PHP. 

Any reason why the best answer set at column has an index? Am I going to see another PR related to sorting in the discussion list? 👀

**Comment by imorland** [comment]
Thanks for the fast response!

I'm pushing the attribute again after the save due to a strange redraw issue I faced, where when the answer is set, the time initially sets, then jumps back to `invalid time`, until a page refresh. If you have any suggestions on alternative here, I'd be happy to make changes :)

You guess correctly, one of the following PRs will indeed be sorting the discussion list, hence the index

**Comment by datitisev** [comment]
Nah, no need to make changes. I'll play around with it and see if I find any other solution, otherwise it works just fine - just looked odd to me.

I'll be merging this now. Thank you very much!

**Comment by imorland** [comment]
Awesome, thank you!

Next up will be 'awarded best answer' notifications 😃

**Comment by datitisev** [comment]
Looks like the invalid date came from the serializer attribute not being formatted into a date string and sending back a weird object.

Committed that fix and another one I noticed (bug if post discussion & user relationships haven't loaded) in 25dc349.

**Comment by imorland** [comment]
Ah, yes of course. Great spot, thanks again!

**Pull request merged**
