### PR TITLE
Use beta 13 extenders

### PR DESCRIPTION
**Pull request by imorland**
- Use new model extender
- Replace Extend\Compat

### CODE REVIEW

**Comment by imorland** [comment]
I think this covers the extenders, anything I've missed @datitisev ?

**Comment by datitisev** [comment]
As you are using the native Flarum console extender, I'm not sure if the job would be executed with `php flarum schedule:run`.

**Comment by imorland** [comment]
It does indeed run using `php flarum schedule:run` - tested locally

**Comment by KyrneDev** [comment]
Merged, will be released with mobile UI fixes.

**Pull request merged**
